### PR TITLE
Create zh_TW.json

### PR DESCRIPTION
**Pull request by bobbytung**
Add l10n zh_TW (Traditional Chinese, Taiwan) json.

### CODE REVIEW

**Comment by tofi86** [comment]
Hi,

thanks a lot for contributing `zh_TW` locale! That is awesome! 👏 

I will create a new beta build for you which includes `zh_TW` so you can test.

----

Offtopic:

Have you also contributed `zh_TW` translations to the official EPUBCheck library via Transifex? If so, please leave me a note at https://github.com/w3c/epubcheck/pull/991 so I can add you to the list of contributors. Unfortunately we cannot see who translated what, that's why I'm asking...

**Comment by tofi86** [comment]
Rebased your branch on current pagina `master` with Czech translations.

Adding zh_TW now.

**Comment by tofi86** [comment]
Added all files and pushed to `bobbytung/master` branch.

@bobbytung as far as I read `zh_TW` is the default language code for "Traditional Chinese". Shall I call it like this or shall I write "Traditional Chinese (Taiwan)" because it would confuse other chinese speaker otherwise?

Also, I need two more translations from you, marked with `***TODO***` in the JSON file. Can you edit the document here: https://github.com/bobbytung/EPUB-Checker/edit/master/src/main/resources/localization/zh_TW.json and translate the strings?

Thanks!

**Comment by bobbytung** [comment]
> @bobbytung Shall I call it like this or shall I write "Traditional Chinese (Taiwan)" 

sure, that's the best.
 
> Also, I need two more translations from you, marked with `***TODO***` in the JSON file. 

Done!

And I just found that Japanese l10n is incomplete, should I notice translators to complete it?

**Comment by tofi86** [comment]
Alright, thanks a lot! 👏 

Regarding Japanese: I have to revise first. There have been a couple of messages in these JSON files which are now part of the official EPUBCheck and doesn't need to be translated. If I need help, I will let you know.

**Comment by tofi86** [comment]
I uploaded a beta build which includes zh_TW and which can be tested by you if you like:

Mac: https://download.pagina.gmbh/epubchecker/beta/EPUB-Checker-1.8.1-SNAPSHOT-dist-mac.zip
Windows: https://download.pagina.gmbh/epubchecker/beta/EPUB-Checker-1.8.1-SNAPSHOT-dist-win.zip

If you need to change some translations, please edit this file and send a new PullRequest: https://github.com/paginagmbh/EPUB-Checker/edit/master/src/main/resources/localization/zh_TW.json

**Pull request merged**
