### PR TITLE
add Japanese translation

### PR DESCRIPTION
**Pull request by takahashim**
I've translated messages into Japanese.

### CODE REVIEW

**Comment by tofi86** [comment]
Hi @takahashim, thanks a lot for your contribution to our @paginagmbh EPUB-Checker GUI! 🎉 

The changes look great, I tested different modes and messages, although I don't understand Japanese, but overall it looks very good! And you spotted all places where changes are needed due to additional language.

Merged this, thanks!
However, I will not release a new version of the GUI until [IDPF/epubcheck v4.1.0](https://github.com/IDPF/epubcheck/milestone/3) is released. And this should be very soon, hopefully!

But if you like I could build a codesigned beta-version in the meantime, only for you and your colleagues... Just give me a shout!

**Comment by takahashim** [comment]
Thanks to merge!
I think the issue #23 is very important and should be solved for us to use localized EPUB-Checker, so it's OK to release new EPUB-Checker after releasing epubcheck v4.1.0 👍

**Comment by tofi86** [comment]
Perfect! I'll keep you updated on the release-roadmap. YOu can also follow the IDPF release with the link above.

**Comment by tofi86** [comment]
Hi @takahashim,

unfortunately EpubCheck development stalled.

I decided to ship a maintenance release v1.7.2 which contains your translations:

https://twitter.com/paginagmbh/status/1024046648345944064

One again: Thank you very much for your contribution!

Regards,
Tobias

**Pull request merged**
