### PR TITLE
Update pt_BR.json

### PR DESCRIPTION
**Pull request by thiagoeec**
Update translation.

### CODE REVIEW

**Comment by tofi86** [comment]
Thanks! Can you also translate line 53 please?

**Comment by tofi86** [comment]
And can you please check lines 15-24, the translated language names in ( ). I think I did them with Google translate one day 🙈

**Comment by thiagoeec** [comment]
> Thanks! Can you also translate line 53 please?

Done!

> And can you please check lines 15-24, the translated language names in ( ). I think I did them with Google translate one day 🙈

Those look ok! =)

**Comment by thiagoeec** [comment]
I accidentally closed the pull request.

**Comment by tofi86** [comment]
Perfect, thanks a lot! :-)

**Pull request merged**
